version: '3.4'

services:
  countrydictionaryapiapp:
    image: ${DOCKER_REGISTRY-}countrydictionaryapiapp
    build:
      context: .
      dockerfile: CountryDictionaryApiApp/Dockerfile
    ports:
      - 80:8080
    networks:
      internal:
        ipv4_address: 10.5.0.5
    depends_on:
      - countrydictionaryapidb
  
  countrydictionaryapidb:
    image: postgres:latest
    container_name: countrydictionaryapidb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      internal:
        ipv4_address: 10.5.0.6

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
